baseURL = 'https://walissonaguirra.dev/'
copyright = "{year}"
defaultContentLanguage = 'pt-br'
defaultContentLanguageInSubdir = true
theme = 'enchanted-lowkey'
title = 'Walisson Aguirra'
enableRobotsTXT = true
summaryLength = 15

[languages]
  [languages.pt-br]
    languageCode = 'pt-BR'
    languageName = 'Português'
    contentDir = 'content/pt-br'
    weight = 1
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2

[pagination]
  pagerSize = 5

[services]
  [services.googleAnalytics]
    ID = "G-8KWK0N3QQ6"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 4
